# Generated by Django 5.2.7 on 2026-02-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='joined_by_marriage',
            field=models.BooleanField(default=False),
        ),
    ]
