# Generated by Django 5.2.7 on 2026-02-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyApp', '0002_person_joined_by_marriage'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
